FROM mcr.microsoft.com/powershell:7.3-ubuntu-22.04

LABEL org.opencontainers.image.title="PowerShell" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.description='MicroSoft PowerShell 7.3'

CMD ["pwsh"]
