FROM centos:7.8.2003

LABEL MAINTAINER="Cloudflying" \
    MAIL="<oss@live.hk>" \
    org.opencontainers.image.source=https://github.com/dockenv/dockenv \
    org.opencontainers.image.description="CentOS 7.8 Docker Images"

CMD [ "bash" ]
