FROM mcr.microsoft.com/powershell:ubuntu-22.04

LABEL MAINTAINER="Cloudflying" \
    MAIL="oss@live.hk" \
    org.opencontainers.image.source=https://github.com/dockenv/dockenv-images\
    org.opencontainers.image.description='PowerShell latest'

CMD ["pwsh"]
