FROM photon:latest

LABEL org.opencontainers.image.title="Photon" \
  org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
  org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
  org.opencontainers.image.description='an open source minimal Linux container host.'

CMD [ "/usr/bin/bash" ]
