FROM mcr.microsoft.com/powershell:lts-7.2-ubuntu-22.04

LABEL org.opencontainers.image.title="PowerShell" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.description='MicroSoft PowerShell 7.2'

CMD ["pwsh"]
