# Ubuntu 20.10
FROM ubuntu:groovy
LABEL org.opencontainers.image.title="Ubuntu Linux" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='Ubuntu: Enterprise Linux distribution based on Debian.'

ENV PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"

CMD ["/usr/bin/bash"]
