FROM oraclelinux:9-slim
LABEL org.opencontainers.image.title="Oracle Linux" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='open-source operating system available under the GNU General Public License (GPLv2).'

CMD [ "/usr/bin/bash" ]
