FROM mcr.microsoft.com/powershell:preview-7.4-ubuntu-22.04

LABEL MAINTAINER="Cloudflying" \
    MAIL="oss@live.hk" \
    org.opencontainers.image.source=https://github.com/dockenv/dockenv-images\
    org.opencontainers.image.description='PowerShell 7.4'

CMD ["pwsh"]
