FROM python:2.7-alpine

LABEL org.opencontainers.image.title="Python" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='Python Language 2.7'

CMD ["python2"]
