FROM eclipse-temurin:8-jre-noble

LABEL org.opencontainers.image.title="OpenJDK" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://github.com/dockenv" \
      org.opencontainers.image.description='OpenJDK by Eclipse Temurin.'

ENTRYPOINT ["/__cacert_entrypoint.sh"]