FROM mcr.microsoft.com/dotnet/runtime:9.0-alpine

LABEL org.opencontainers.image.title="Dotnet Runtime" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://github.com/dockenv" \
      org.opencontainers.image.description='.NET is a cross-platform runtime for cloud, mobile, desktop, and IoT apps.'