FROM ghcr.io/dockenv/alpine:3.16

LABEL org.opencontainers.image.title="Node" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/imxieke/dockenv-images" \
      org.opencontainers.image.description='Node 16'

RUN apk add --no-cache nodejs npm yarn

CMD [ "node" ]
