FROM dicedb/dicedb:latest
LABEL org.opencontainers.image.title="Dice DB" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='DiceDB is an open-source, fast, reactive, in-memory database optimized for modern hardware.'

EXPOSE 7379