FROM almalinux:8.9-minimal
LABEL org.opencontainers.image.title="Almalinux" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='AlmaLinux OS is an Open Source and forever-free enterprise Linux distribution.'

CMD [ "/usr/bin/bash" ]
