FROM cassandra:5.0-jammy

LABEL org.opencontainers.image.title="Cassandra" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='Apache Cassandra is an open-source distributed storage system.'

VOLUME /var/lib/cassandra

# 7000: intra-node communication
# 7001: TLS intra-node communication
# 7199: JMX
# 9042: CQL
# 9160: thrift service
EXPOSE 7000 7001 7199 9042 9160
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["cassandra", "-f"]