FROM typesense/typesense:26.0-amd64

LABEL org.opencontainers.image.title="Typesense" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='⚡🔍 Fast, typo tolerant, fuzzy search engine for building delightful search experiences.'

EXPOSE 8108
ENTRYPOINT ["/opt/typesense-server"]