FROM centos:7.9.2009

LABEL MAINTAINER="Cloudflying" \
    MAIL="<oss@live.hk>" \
    org.opencontainers.image.source=https://github.com/dockenv/dockenv \
    org.opencontainers.image.description="CentOS 7.9 Docker Images"

CMD [ "bash" ]
