FROM mageia:7
LABEL org.opencontainers.image.title="Mageia" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='Mageia is a GNU/Linux-based, Free Software operating system.'

CMD [ "/usr/bin/bash" ]
