FROM julia:1.6-alpine

LABEL org.opencontainers.image.title="Julia" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='Julia is a high-level, high-performance dynamic programming language for technical computing.'

CMD ["julia"]
