FROM quay.io/centos/centos:stream9-development

LABEL MAINTAINER="Cloudflying" \
    MAIL="<oss@live.hk>" \
    org.opencontainers.image.source=https://github.com/dockenv/dockenv \
    org.opencontainers.image.description="CentOS stream 9 dev Docker Images"

CMD [ "bash" ]
