FROM fedora:42

LABEL org.opencontainers.image.title="Fedora" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://github.com/dockenv" \
      org.opencontainers.image.description='a Linux distribution developed by the Fedora Project.'

CMD ["/bin/bash"]