FROM ghcr.io/dockenv/debian:latest

LABEL org.opencontainers.image.title="Debian GNU Linux" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='Debian GNU Linux Bookworm'

ENV DEBIAN_FRONTEND=noninteractive

RUN apt install xfce4