FROM aerospike:ee-6.3.0.1_1
LABEL org.opencontainers.image.title="Aerospike" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='Aerospike – the reliable, high performance, distributed database optimized for flash and RAM.'

EXPOSE 3000 3001 3002

CMD ["asd"]