FROM node:22-alpine

LABEL org.opencontainers.image.title="Node" \
  org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
  org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
  org.opencontainers.image.description='a JavaScript-based platform for server-side and networking applications.'

CMD [ "node" ]
