shadowsocks:
  image: ghcr.io/dockenv/shadowsocks:latest
  ports:
    - "6443:6443/tcp"
    - "6443:6443/udp"
  environment:
    - PORT=6443
    - METHOD=chacha20-ietf-poly1305
    - PASSWORD=dockpass
  restart: always
