FROM amazonlinux:latest

LABEL org.opencontainers.image.title="Amazon Linux" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='Amazon Linux'

CMD ["/bin/bash"]
