FROM elasticsearch:6.8.23

LABEL org.opencontainers.image.title="Elasticsearch" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='A powerful open source search and analytics engine that makes data easy to explore.'

EXPOSE 9200 9300
CMD ["eswrapper"]
