FROM mcr.microsoft.com/dotnet/sdk:9.0-preview-alpine

LABEL org.opencontainers.image.title="Dotnet" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://github.com/dockenv" \
      org.opencontainers.image.description='a general purpose development platform.'