FROM python:3.10-alpine

LABEL org.opencontainers.image.title="Python" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='Python Language 3.10'

CMD ["python3"]
