FROM redhat/ubi9-minimal:latest

LABEL MAINTAINER="Cloudflying" \
    MAIL="<oss@live.hk>" \
    org.opencontainers.image.source=https://github.com/dockenv/dockenv \
    org.opencontainers.image.description="RHEL Docker Images"

CMD ["bash"]
