FROM swr.ap-southeast-3.myhuaweicloud.com/dockenv/alpine:latest

LABEL MAINTAINER="Cloudflying" \
        MAIL="oss@live.hk" \
        org.opencontainers.image.source=https://github.com/dockenv/dockenv

RUN apk add --no-cache acme.sh

CMD ["/bin/ash"]
