FROM ghcr.io/dockenv/alpine:3.16

LABEL org.opencontainers.image.title="Nginx Unit"
LABEL org.opencontainers.image.vendor="Cloudflying <oss@live.hk>"
LABEL org.opencontainers.image.source="https://github.com/dockenv/dockenv-images"
LABEL org.opencontainers.image.description='Nginx Unit'

RUN apk add --no-cache unit unit-php8 unit-python3
