FROM ghcr.io/dockenv/alpine:latest

LABEL org.opencontainers.image.title="Nginx Unit"
LABEL org.opencontainers.image.vendor="Cloudflying <oss@live.hk>"
LABEL org.opencontainers.image.source="https://github.com/dockenv/dockenv-images"
LABEL org.opencontainers.image.description='Nginx Unit'

RUN apk add --no-cache unit unit-php81 unit-php82 unit-python3 unit-ruby unit-tools
