FROM ruby:3.3-rc-alpine

LABEL org.opencontainers.image.title="Ruby" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='Rby Language 3.3 RC'

CMD [ "irb" ]
