# hadolint ignore=DL3007
FROM opensuse/leap:latest
LABEL org.opencontainers.image.title="openSUSE Leap" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='openSUSE Leap is a stable, easy to use and complete multi-purpose distribution.'

CMD ["/bin/bash"]
