# hadolint ignore=DL3007
FROM dart:3.1
LABEL org.opencontainers.image.title="Dart" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='Dart is a client-optimized language for fast apps on any platform.'
