# hadolint ignore=DL3007
FROM traefik:3.0
LABEL org.opencontainers.image.title="Traefik" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='Traefik, The Cloud Native Edge Router'

EXPOSE 80 8080
CMD ["traefik"]