FROM centos:8.2.2004

LABEL MAINTAINER="Cloudflying" \
    MAIL="<oss@live.hk>" \
    org.opencontainers.image.source=https://github.com/dockenv/dockenv \
    org.opencontainers.image.description="CentOS 8.2 Docker Images"

CMD [ "bash" ]
