FROM quay.io/centos/centos:stream

LABEL MAINTAINER="Cloudflying" \
    MAIL="<oss@live.hk>" \
    org.opencontainers.image.source=https://github.com/dockenv/dockenv \
    org.opencontainers.image.description="CentOS stream Docker Images"

CMD [ "bash" ]
