FROM mcr.microsoft.com/dotnet/aspnet:9.0-preview-alpine

LABEL org.opencontainers.image.title="aspnet" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://github.com/dockenv" \
      org.opencontainers.image.description='an open-source and cross-platform framework for building modern cloud-based internet-connected applications.'