version: '2.2'

services:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.4.3
    environment:
      ELASTICSEARCH_URL: http://10.0.72.173:9200
    ports:
      - 5601:5601