version: '2'

services:
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:6.4.3
    user: root
    container_name: metricbeat
    environment:
      - setup.kibana.host=
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro