FROM rustfs/rustfs:latest

LABEL org.opencontainers.image.title="RustFS" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='🚀 High-performance distributed object storage for MinIO alternative.'
