# This is the yaml configuration file for dnsproxy with minimal working
# configuration, all the options available can be seen with ./dnsproxy --help.
# To use it within dnsproxy specify the --config-path=/<path-to-config.yaml>
# option.  Any other command-line options specified will override the values
# from the config file.
---
bootstrap:
  - "8.8.8.8:53"
  - "2620:fe::10:53"
listen-addrs:
  - "0.0.0.0"
tls-ports: 843
https-ports: 443
listen-ports: 53
quic-port: 443
dnscrypt-port: 4443
max-go-routines: 0
ratelimit: 0
ratelimit-subnet-len-ipv4: 24
ratelimit-subnet-len-ipv6: 64
udp-buf-size: 0
upstream:
  - "1.1.1.1:53"
  - "8.8.8.8:53"
  - "tls://dns.adguard.com"
  - "https://dns.alidns.com/dns-query"
  - "quic://dns.adguard.com"
  - "https://dns.google/dns-query"
fallback:
  - "1.1.1.1:53"
timeout: '10s'
output: "/tmp/dnsproxy.log"