FROM mcr.microsoft.com/azurelinux/base/core:3.0

LABEL org.opencontainers.image.title="Azure Linux" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://github.com/dockenv" \
      org.opencontainers.image.description='Azure Linux is a Linux distribution for Microsoft’s cloud infrastructure and edge products and services.'