FROM ghcr.io/dockenv/alpine:3.18

LABEL org.opencontainers.image.title="Node" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.description='Node 18'

RUN apk add --no-cache nodejs npm yarn

CMD [ "node" ]
