FROM ghcr.io/dockenv/alpine:3.18

LABEL org.opencontainers.image.title="Node"
LABEL org.opencontainers.image.vendor="Cloudflying <oss@live.hk>"
LABEL org.opencontainers.image.source="https://github.com/imxieke/dockenv-images"
LABEL org.opencontainers.image.description='Nodejs 18'

RUN apk add --no-cache nodejs npm yarn

CMD [ "node" ]
