FROM centos:7.1.1503

LABEL org.opencontainers.image.title="Centos" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='Community-driven free software effort focused around the goal of providing a rich base platform for open source communities to build upon.'

CMD ["/usr/bin/bash"]
