name: Weekly Docker Build Software

on:
  workflow_dispatch:
  schedule:
    # 每周一晚 2 点.
    - cron: '0 2 * * 1'

env:
  TZ: Asia/Shanghai
  REGISTRY: ghcr.io

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . -f images/geckodriver/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/geckodriver:latest
        docker build . -f images/chromedriver/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/chromedriver:latest
        docker build . -f images/rsync/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/rsync:latest
        docker build . -f images/acme/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/acme:latest
        docker build . -f images/beanstalkd/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/beanstalkd:latest
        docker build . -f images/beanstalkd/1.12/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/beanstalkd:1.12
        docker build . -f images/haproxy/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/haproxy:latest
        docker build . -f images/influxdb/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/influxdb:latest
        docker build . -f images/pgadmin4/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/pgadmin4:latest
        docker build . -f images/portainer/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/portainer:latest
        docker build . -f images/postgres/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/postgres:latest
        docker build . -f images/rabbitmq/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/rabbitmq:latest
        docker build . -f images/memcached/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/memcached:latest
        docker build . -f images/caddy/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/caddy:latest
        docker build . -f images/varnish/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/varnish:latest
        docker build . -f images/rust/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/rust:latest
        docker build . -f images/gitea/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/gitea:latest
        docker build . -f images/elixir/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/elixir:latest
        docker build . -f images/unit/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/unit:latest

    - name: Login Github Package Registry
      run: |
        docker login -u ${{vars.USERNAME}} -p "${{ secrets.APIKEY }}" ${{ vars.DOCKER_REGISTRY_GITHUB }}

    - name: Push Docker Image To Github Package
      run: |
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/acme:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/beanstalkd:1.12
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/beanstalkd:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/chromedriver:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/caddy:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/geckodriver:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/gitea:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/haproxy:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/influxdb:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/pgadmin4:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/portainer:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/postgres:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/rabbitmq:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/memcached:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/rsync:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/rust:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/varnish:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/elixir:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/unit:latest
