name: Docker Build Linux Images

on:
  workflow_dispatch:
    branches:
    - master
  schedule:
    - cron: '0 2 * * 1'

env:
  REGISTRY: ghcr.io

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Linux Docker image
      run: |
        docker build . -f images/archlinux/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/archlinux:latest
        docker build . -f images/gentoo/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/gentoo:latest
        docker build . -f images/manjaro/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/manjaro:latest
        docker build . -f images/almalinux/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/almalinux:latest
        docker build . -f images/almalinux/8.4/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/almalinux:8.4
        docker build . -f images/amazonlinux/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/amazonlinux:latest
        docker build . -f images/busybox/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/busybox:latest
        docker build . -f images/busybox/glibc/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/busybox:glibc
        docker build . -f images/busybox/musl/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/busybox:musl
        docker build . -f images/kali/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/kali:latest
        docker build . -f images/rockylinux/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/rockylinux:latest
        docker build . -f images/rockylinux/8/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/rockylinux:8
        docker build . -f images/scientificlinux/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/scientificlinux:latest
        docker build . -f images/scientificlinux/7/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/scientificlinux:7
        docker build . -f images/voidlinux/musl/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/voidlinux:musl
        docker build . -f images/voidlinux/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/voidlinux:latest

    - name: Login Github Package Registry
      run: |
        docker login -u ${{vars.USERNAME}} -p "${{ secrets.APIKEY }}" ${{ vars.DOCKER_REGISTRY_GITHUB }}

    - name: Push Docker Image To Github Package
      run: |
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/archlinux:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/gentoo:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/manjaro:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/almalinux:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/almalinux:8.4
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/amazonlinux:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/busybox:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/busybox:glibc
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/busybox:musl
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/kali:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/rockylinux:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/rockylinux:8
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/scientificlinux:latest
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/scientificlinux:7
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/voidlinux:musl
        docker push ${{ vars.DOCKER_REGISTRY_GITHUB }}/dockenv/voidlinux:latest
