name: Docker Build Linux Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Linux Docker image
        run: |
          docker build . -f images/cirros/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY }}/dockenv/cirros:latest
          docker build . -f images/manjaro/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY }}/dockenv/manjaro:latest
          docker build . -f images/gentoo/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY }}/dockenv/gentoo:latest
          docker build . -f images/kali/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY }}/dockenv/kali:latest
          docker build . -f images/busybox/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY }}/dockenv/busybox:latest
          docker build . -f images/busybox/glibc/Dockerfile -t ${{ vars.DOCKER_REGISTRY }}/dockenv/busybox:glibc
          docker build . -f images/busybox/musl/Dockerfile -t ${{ vars.DOCKER_REGISTRY }}/dockenv/busybox:musl
          docker build . -f images/scientificlinux/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY }}/dockenv/scientificlinux:latest
          docker build . -f images/scientificlinux/7/Dockerfile -t ${{ vars.DOCKER_REGISTRY }}/dockenv/scientificlinux:7
          docker build . -f images/voidlinux/musl/Dockerfile -t ${{ vars.DOCKER_REGISTRY }}/dockenv/voidlinux:musl
          docker build . -f images/voidlinux/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY }}/dockenv/voidlinux:latest
          docker build . -f images/clearlinux/latest/Dockerfile -t ${{ vars.DOCKER_REGISTRY }}/dockenv/clearlinux:latest
          docker build . -f images/clearlinux/base/Dockerfile -t ${{ vars.DOCKER_REGISTRY }}/dockenv/clearlinux:base

      - name: Login to Docker Registry
        run: |
          docker login -u ${{vars.USERNAME}} -p "${{ secrets.APIKEY }}" ${{ vars.DOCKER_REGISTRY }}

      - name: Push Docker Image
        run: |
          docker push ${{ vars.DOCKER_REGISTRY }}/dockenv/gentoo:latest
          docker push ${{ vars.DOCKER_REGISTRY }}/dockenv/manjaro:latest
          docker push ${{ vars.DOCKER_REGISTRY }}/dockenv/busybox:latest
          docker push ${{ vars.DOCKER_REGISTRY }}/dockenv/busybox:glibc
          docker push ${{ vars.DOCKER_REGISTRY }}/dockenv/busybox:musl
          docker push ${{ vars.DOCKER_REGISTRY }}/dockenv/kali:latest
          docker push ${{ vars.DOCKER_REGISTRY }}/dockenv/scientificlinux:latest
          docker push ${{ vars.DOCKER_REGISTRY }}/dockenv/scientificlinux:7
          docker push ${{ vars.DOCKER_REGISTRY }}/dockenv/voidlinux:musl
          docker push ${{ vars.DOCKER_REGISTRY }}/dockenv/voidlinux:latest
          docker push ${{ vars.DOCKER_REGISTRY }}/dockenv/clearlinux:latest
          docker push ${{ vars.DOCKER_REGISTRY }}/dockenv/clearlinux:base
          docker push ${{ vars.DOCKER_REGISTRY }}/dockenv/cirros:latest
