FROM registry.access.redhat.com/rhel-minimal:latest

LABEL MAINTAINER="Cloudflying" \
    MAIL="<oss@live.hk>" \
    org.opencontainers.image.source=https://github.com/dockenv/dockenv-images\
    org.opencontainers.image.description="RHEL Docker Images"

CMD ["bash"]
