# hadolint ignore=DL3007
FROM swift:latest
LABEL org.opencontainers.image.title="Swift" \
      org.opencontainers.image.authors="Cloudflying <oss@live.hk>" \
      org.opencontainers.image.source="https://github.com/dockenv/dockenv-images" \
      org.opencontainers.image.url="https://dockenv.github.io" \
      org.opencontainers.image.description='Swift is a high-performance system programming language.'